alias: Notification Light - Incoming WhatsApp Call Flash
description: Flash lights on incoming WhatsApp call
triggers:
  - entity_id:
      - sensor.sm_a715f_last_notification
      - sensor.new_phone_last_notification
    trigger: state
conditions:
  - condition: template
    value_template: |-
      {{ trigger.entity_id in [
           'sensor.sm_a715f_last_notification',
           'sensor.new_phone_last_notification']
         and state_attr(trigger.entity_id, 'package') == 'com.whatsapp'
         and state_attr(trigger.entity_id, 'category') == 'call'
         and 'incoming voice call' in state_attr(trigger.entity_id, 'android.text')|lower }}
actions:
  - target:
      entity_id: script.flash_alert_lights
    data:
      variables:
        light_group: light.light_group_incoming_call_flash
        col1: green
        col2: white
        brightness_high: 80
        brightness_low: 20
        flash_count: 4
        flash_delay: "00:00:02"
    action: script.turn_on
mode: single
