alias: Notification Light - Incoming Cellular Call Flash
description: Colour flash lights on incoming calls and return lights to previous state
triggers:
  - entity_id:
      - sensor.sm_a715f_phone_state
    to: ringing
    trigger: state
conditions:
  - condition: template
    value_template: >-
      {% set phones = [
        'sensor.sm_a715f_last_notification'
      ] %} {% set ns = namespace(is_whatsapp_call = false) %} {% for s in phones
      %}
        {% if state_attr(s, 'package') == 'com.whatsapp'
           and (state_attr(s, 'category') or '') | lower == 'call'
           and 'incoming voice call' in ((state_attr(s, 'android.text') or '') | lower) %}
          {% set ns.is_whatsapp_call = true %}
        {% endif %}
      {% endfor %} {{ not ns.is_whatsapp_call }}
actions:
  - target:
      entity_id: script.flash_alert_lights
    data:
      variables:
        light_group: light.light_group_incoming_call_flash
        col1: blue
        col2: white
        brightness_high: 80
        brightness_low: 20
        flash_count: 4
        flash_delay: "00:00:02"
    action: script.turn_on
mode: single
